### ISSUE TITLE
v2.1.11 Panel shows error 'l.add is not a function' when no data returned from queries on Grafana 9.5.14

### ISSUE THREAD

**Issue by tiantangkuohai** [grafana/grafana-polystat-panel#387]
When query returns no data, polystat panel will show 'l.add is not a function' in title. And here's browser console output:
TypeError: l.add is not a function
    at eval (deframer.ts:51:9)
    at Oo (processor.ts:73:23)
    at eval (PolystatPanel.tsx:39:29)
    at Od (react-dom.production.min.js:262:359)
    at g.unstable_runWithPriority (scheduler.production.min.js:18:343)
    at nu (react-dom.production.min.js:122:325)
    at Xf (react-dom.production.min.js:261:308)
    at Gl (react-dom.production.min.js:243:50)
    at react-dom.production.min.js:123:115
<img width="635" alt="image" src="https://github.com/grafana/grafana-polystat-panel/assets/31265288/d33f2161-02b4-4319-bec6-9871a22d1286">

**Comment by briangann** [comment]
I did reproduce this error, this is due to removal of VectorArray in v9.5 (was deprecated then finally removed).

I am preparing a workaround to retain compatibility with older versions of the grafana runtime.
