### ISSUE TITLE
Cannot read properties of undefined (reading 'x') in grafana 11.1

### ISSUE THREAD

**Issue by andrejshapal** [grafana/grafana-polystat-panel#404]
Hello,

Polystat panel always gives error:
```
TypeError: Cannot read properties of undefined (reading 'x')
    at $ (Polystat.tsx:245:40)
    at Polystat.tsx:561:28
    at Array.map (<anonymous>)
    at zt (Polystat.tsx:560:35)
    at Lf (react-dom.production.min.js:167:137)
    at ln (react-dom.production.min.js:290:337)
    at Zh (react-dom.production.min.js:280:389)
    at Nd (react-dom.production.min.js:280:320)
    at yh (react-dom.production.min.js:280:180)
    at xf (react-dom.production.min.js:271:88)
```
Can be reproduced with query:
`container_cpu_usage_seconds_total{}` 

Grafana v11.1.0
grafana-polystat-panel v2.1.12

**Comment by tiantangkuohai** [comment]
+1

**Comment by EdisonRobertoJr** [comment]
Same here, but only happens when I have a 'Display Limit' set and probably the number of results is greater than the limit.

![Image](https://github.com/user-attachments/assets/b652ad6e-caf4-47b4-a884-33101ab642e3)

**Comment by glerma** [comment]
Same issue for me when I have the default 'Display limit' of 100 and there are a lot of hosts to render.

Grafana: 10.0.1
Polystat: 2.1.13

**Comment by tiantangkuohai** [comment]
Any release plan for this bugfix? ☺

**Comment by slaughtlaught** [comment]
Same issue for me 

Grafana: 11.2.7
Polystat: 2.1.13

**Comment by briangann** [comment]
Fixed in v2.1.15
